apiVersion: skaffold/v1beta12
kind: Config
build:
 tagPolicy:
   sha256: {}
 artifacts:
 - image: belaboros/greeting
 local:
   useBuildkit: true
deploy:
 kubectl:
   manifests:
     - k8s/greeting-deployment.yml




